/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TimeLock__factory } from "./TimeLock__factory";
export { TimeLockAdvanced__factory } from "./TimeLockAdvanced__factory";
