/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface TimeLockAdvancedInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createVault"
      | "getTotalLocked"
      | "getVaultInfo"
      | "hasAuthorityRight"
      | "setReceiver"
      | "setUnlockTime"
      | "vaultCount"
      | "vaults"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ReceiverChanged"
      | "UnlockTimeChanged"
      | "VaultCreated"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createVault",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalLocked",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultInfo",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasAuthorityRight",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setReceiver",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setUnlockTime",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vaults",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalLocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasAuthorityRight",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUnlockTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vaultCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vaults", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace ReceiverChangedEvent {
  export type InputTuple = [
    creator: AddressLike,
    vaultId: BigNumberish,
    newReceiver: AddressLike
  ];
  export type OutputTuple = [
    creator: string,
    vaultId: bigint,
    newReceiver: string
  ];
  export interface OutputObject {
    creator: string;
    vaultId: bigint;
    newReceiver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnlockTimeChangedEvent {
  export type InputTuple = [
    creator: AddressLike,
    vaultId: BigNumberish,
    newUnlockTime: BigNumberish
  ];
  export type OutputTuple = [
    creator: string,
    vaultId: bigint,
    newUnlockTime: bigint
  ];
  export interface OutputObject {
    creator: string;
    vaultId: bigint;
    newUnlockTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultCreatedEvent {
  export type InputTuple = [
    creator: AddressLike,
    vaultId: BigNumberish,
    receiver: AddressLike,
    authority: AddressLike,
    amount: BigNumberish,
    unlockTime: BigNumberish,
    authorityRights: BigNumberish
  ];
  export type OutputTuple = [
    creator: string,
    vaultId: bigint,
    receiver: string,
    authority: string,
    amount: bigint,
    unlockTime: bigint,
    authorityRights: bigint
  ];
  export interface OutputObject {
    creator: string;
    vaultId: bigint;
    receiver: string;
    authority: string;
    amount: bigint;
    unlockTime: bigint;
    authorityRights: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    receiver: AddressLike,
    vaultId: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [receiver: string, vaultId: bigint, amount: bigint];
  export interface OutputObject {
    receiver: string;
    vaultId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TimeLockAdvanced extends BaseContract {
  connect(runner?: ContractRunner | null): TimeLockAdvanced;
  waitForDeployment(): Promise<this>;

  interface: TimeLockAdvancedInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createVault: TypedContractMethod<
    [
      _receiver: AddressLike,
      _authority: AddressLike,
      _lockDuration: BigNumberish,
      _authorityRights: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  getTotalLocked: TypedContractMethod<
    [_creator: AddressLike],
    [bigint],
    "view"
  >;

  getVaultInfo: TypedContractMethod<
    [_creator: AddressLike, _vaultId: BigNumberish],
    [
      [string, string, string, bigint, bigint, bigint, boolean, boolean] & {
        creator: string;
        authority: string;
        receiver: string;
        amount: bigint;
        unlockTime: bigint;
        authorityRights: bigint;
        withdrawn: boolean;
        isUnlocked: boolean;
      }
    ],
    "view"
  >;

  hasAuthorityRight: TypedContractMethod<
    [_creator: AddressLike, _vaultId: BigNumberish, _right: BigNumberish],
    [boolean],
    "view"
  >;

  setReceiver: TypedContractMethod<
    [_creator: AddressLike, _vaultId: BigNumberish, _newReceiver: AddressLike],
    [void],
    "nonpayable"
  >;

  setUnlockTime: TypedContractMethod<
    [
      _creator: AddressLike,
      _vaultId: BigNumberish,
      _newUnlockTime: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  vaultCount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  vaults: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, string, bigint, bigint, bigint, boolean] & {
        creator: string;
        authority: string;
        receiver: string;
        amount: bigint;
        unlockTime: bigint;
        authorityRights: bigint;
        withdrawn: boolean;
      }
    ],
    "view"
  >;

  withdraw: TypedContractMethod<
    [_creator: AddressLike, _vaultId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createVault"
  ): TypedContractMethod<
    [
      _receiver: AddressLike,
      _authority: AddressLike,
      _lockDuration: BigNumberish,
      _authorityRights: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getTotalLocked"
  ): TypedContractMethod<[_creator: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVaultInfo"
  ): TypedContractMethod<
    [_creator: AddressLike, _vaultId: BigNumberish],
    [
      [string, string, string, bigint, bigint, bigint, boolean, boolean] & {
        creator: string;
        authority: string;
        receiver: string;
        amount: bigint;
        unlockTime: bigint;
        authorityRights: bigint;
        withdrawn: boolean;
        isUnlocked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasAuthorityRight"
  ): TypedContractMethod<
    [_creator: AddressLike, _vaultId: BigNumberish, _right: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "setReceiver"
  ): TypedContractMethod<
    [_creator: AddressLike, _vaultId: BigNumberish, _newReceiver: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setUnlockTime"
  ): TypedContractMethod<
    [
      _creator: AddressLike,
      _vaultId: BigNumberish,
      _newUnlockTime: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vaultCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "vaults"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, string, bigint, bigint, bigint, boolean] & {
        creator: string;
        authority: string;
        receiver: string;
        amount: bigint;
        unlockTime: bigint;
        authorityRights: bigint;
        withdrawn: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [_creator: AddressLike, _vaultId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ReceiverChanged"
  ): TypedContractEvent<
    ReceiverChangedEvent.InputTuple,
    ReceiverChangedEvent.OutputTuple,
    ReceiverChangedEvent.OutputObject
  >;
  getEvent(
    key: "UnlockTimeChanged"
  ): TypedContractEvent<
    UnlockTimeChangedEvent.InputTuple,
    UnlockTimeChangedEvent.OutputTuple,
    UnlockTimeChangedEvent.OutputObject
  >;
  getEvent(
    key: "VaultCreated"
  ): TypedContractEvent<
    VaultCreatedEvent.InputTuple,
    VaultCreatedEvent.OutputTuple,
    VaultCreatedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "ReceiverChanged(address,uint256,address)": TypedContractEvent<
      ReceiverChangedEvent.InputTuple,
      ReceiverChangedEvent.OutputTuple,
      ReceiverChangedEvent.OutputObject
    >;
    ReceiverChanged: TypedContractEvent<
      ReceiverChangedEvent.InputTuple,
      ReceiverChangedEvent.OutputTuple,
      ReceiverChangedEvent.OutputObject
    >;

    "UnlockTimeChanged(address,uint256,uint256)": TypedContractEvent<
      UnlockTimeChangedEvent.InputTuple,
      UnlockTimeChangedEvent.OutputTuple,
      UnlockTimeChangedEvent.OutputObject
    >;
    UnlockTimeChanged: TypedContractEvent<
      UnlockTimeChangedEvent.InputTuple,
      UnlockTimeChangedEvent.OutputTuple,
      UnlockTimeChangedEvent.OutputObject
    >;

    "VaultCreated(address,uint256,address,address,uint256,uint256,uint8)": TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;
    VaultCreated: TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;

    "Withdrawn(address,uint256,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
